version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:601160152322:task-definition/slone-clone-latest:2"
        LoadBalancerInfo:
          ContainerName: "Slack-clone"
          ContainerPort: 8000
