version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 601160152322.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=601160152322.dkr.ecr.us-east-2.amazonaws.com/slone-clone
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t slone-clone .
      - docker tag slone-clone:latest 601160152322.dkr.ecr.us-east-2.amazonaws.com/slone-clone:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 601160152322.dkr.ecr.us-east-2.amazonaws.com/slone-clone:latest
      - echo Writing image definitions file...
      - printf '[{"name":"slone-clone-latest","imageUri":"%s"}]' 601160152322.dkr.ecr.us-east-2.amazonaws.com/slone-clone:latest  > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

