version: '3'
services:
  web:
    image: 601160152322.dkr.ecr.us-east-2.amazonaws.com/slone-clone:latest 
    command: bash -c 'npm run create; npm run migrate:refresh; npm start'
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL_DEV: $DATABASE_URL_DEV
      DATABASE_URL: $DATABASE_URL
      REDIS_HOST: $REDIS_HOST
      SECRET: efe
      CLOUD_NAME: $CLOUD_NAME
      API_KEY: $API_KEY
      API_SECRET: $API_SECRET
      NODEMAILER_USER: $NODEMAILER_USER
      NODEMAILER_PASS: $NODEMAILER_PASS
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/slone-clone-latest
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs
    networks:
      - bridge

  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/slone-clone-latest
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs
    networks:
      - bridge

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: "127.0.0.1"
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/slone-clone-latest
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs
    networks:
      - bridge

networks:
  bridge:

  